name: 'Download Zip from Artifactory'
description: 'Download a file from S3 Artifactory'

branding:
  icon: download-cloud
  color: gray-dark

inputs:
  aws-region:
    required: false
    default: 'ap-south-1'
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  artifactory-bucket:
    description: "The S3 bucket where the files will be downloaded from."
    required: true
  app-path:
    required: true
  artifact:
    required: true
    description: "Versioned zip to be downloaded."

runs:
  using: 'node16'
  main: 'dist/index.js'
